# Generated by Django 3.1.7 on 2021-03-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='wind',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
