# Generated by Django 3.1.7 on 2021-03-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210304_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='info_image',
            field=models.CharField(default='', max_length=30, verbose_name='Id image'),
        ),
    ]
