# Generated by Django 3.1.7 on 2021-03-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weather_info_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='info_image',
            new_name='image',
        ),
    ]
